ocfVersion: 0.0.1
revision: 0.1.0
kind: Type
metadata:
  name: config
  prefix: cap.type.platform-one.big-bang
  displayName: Platform One Big-Bang Installation config
  description: Config for Platform One Installation
  documentationURL: https://p1.dso.mil/#/products/big-bang/
  supportURL: https://p1.dso.mil/#/products/big-bang/
  iconURL: https://p1.dso.mil/img/Big_Bang_Color_Logo_White_text.b04263b1.png
  maintainers:
    - email: team-dev@capact.io
      name: Capact Dev Team
      url: https://capact.io

spec:
  jsonSchema:
    value: |-
      {
        "$schema": "http://json-schema.org/draft-07/schema",
        "type": "object",
        "title": "The schema for Big Bang installation config",
        "examples": [
          {
            "istioGateway": {
              "ip": "1.2.3.4",
              "hostname": "foo.example.com"
            },
            "components": {
              "grafana": {
                "host": "grafana.bigbang.dev",
                "username": "grafana",
                "password": "password"
              }
            }
          }
        ],
        "required": [
            "istioGateway",
            "components"
        ],
        "properties": {
          "istioGateway": {
            "$id": "#/properties/istioGateway",
            "title": "Istio Gateway",
            "properties": {
              "ip": {
                "$id": "#/properties/istioGateway/properties/ip",
                "title": "IP",
                "format": "ipv4",
                "type": "string"
              },
              "hostname": {
                "$id": "#/properties/istioGateway/properties/hostname",
                "title": "Hostname",
                "format": "hostname",
                "type": "string"
              }
            },
            "additionalProperties": false
          },
          "components": {
            "$id": "#/properties/components",
            "type": "object",
            "title": "Big Bang components data",
            "required": [
                "grafana"
            ],
            "properties": {
              "grafana": {
                "$id": "#/properties/components/properties/grafana",
                "type": "object",
                "title": "The Grafana configuration",
                "required": [
                    "host",
                    "username",
                    "password"
                ],
                "properties": {
                  "host": {
                    "$id": "#/properties/components/properties/grafana/properties/host",
                    "type": "string",
                    "format": "uri",
                    "title": "The Grafana host"
                  },
                  "username": {
                    "$id": "#/properties/components/properties/grafana/properties/username",
                    "type": "string",
                    "title": "The Grafana username"
                  },
                  "password": {
                    "$id": "#/properties/components/properties/grafana/properties/password",
                    "type": "string",
                    "title": "The Grafana password"
                  }
                },
                "additionalProperties": false
              }
            },
            "additionalProperties": false
          }
        },
        "additionalProperties": false
      }
