ocfVersion: 0.0.1
revision: 0.1.0
kind: Type
metadata:
  name: install-input
  prefix: cap.type.productivity.bitbucket
  displayName: "Bitbucket installation parameters"
  description: Defines installation parameters for Bitbucket
  documentationURL: https://confluence.atlassian.com/bitbucketserver
  supportURL: https://support.atlassian.com/bitbucket-server/
  maintainers:
    - email: team-dev@capact.io
      name: Capact Dev Team
      url: https://capact.io

spec:
  jsonSchema:
    value: |-
      {
        "$schema": "http://json-schema.org/draft-07/schema",
        "additionalProperties": true,
        "properties": {
          "host": {
            "$id": "#/properties/host",
            "type": "string",
            "title": "Host for BitBucket"
          },
          "sysadminCredentials": {
            "$id": "#/properties/bitbucket/properties/sysadminCredentials",
            "additionalProperties": false,
            "default": {},
            "required": [
              "displayName",
              "emailAddress",
              "password",
              "username"
            ],
            "properties": {
              "displayName": {
                "$id": "#/properties/bitbucket/properties/sysadminCredentials/properties/displayName",
                "default": "displayName",
                "description": "The sysadmin display name",
                "type": "string"
              },
              "emailAddress": {
                "$id": "#/properties/bitbucket/properties/sysadminCredentials/properties/emailAddress",
                "default": "emailAddress",
                "description": "The sysadmin email address",
                "type": "string"
              },
              "password": {
                "$id": "#/properties/bitbucket/properties/sysadminCredentials/properties/password",
                "default": "password",
                "description": "The sysadmin password",
                "type": "string"
              },
              "username": {
                "$id": "#/properties/bitbucket/properties/sysadminCredentials/properties/username",
                "default": "username",
                "description": "The sysadmin username",
                "type": "string"
              }
            },
            "type": "object"
          }
        },
        "type": "object"
      }
